# caching is not supported yet, even though azure supports it as a beta
# the only problem, it does not preserve executable bits which breaks build script and toolchain caching
# the fix is implemented behind an env var which I do not know how to trigger
# https://github.com/microsoft/azure-pipelines-tasks/issues/10841

trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

stages:
  - stage: Build
    jobs:
    - job: Build
      steps:
      - script: git clone --depth=1 --branch=1.39.1 https://github.com/WebAssembly/binaryen && cd binaryen && cmake . && make && sudo make install && cd ..
        displayName: Install dependencies (binaryen)
      - script: rustup default nightly
        displayName: Install Rust nightly
      - script: cargo install wasm-bindgen-cli wasm-pack
        displayName: Install WASM utilities
      - script: ./build.sh
        displayName: Build
    - job: Format
      steps:
      - script: rustup component add rustfmt
        displayName: Install Rustfmt
      - script: rustup default nightly
        displayName: Install Rust nightly
      - script: cargo fmt --all -- --check
        displayName: Cargo Fmt
    - job: Lint
      steps:
      - script: rustup component add clippy
        displayName: Install Clippy
      - script: rustup default nightly
        displayName: Install Rust nightly
      - script: rustup target add wasm32-unknown-unknown
        displayName: Install Rust WASM target
      - script: cargo clippy --all --target=wasm32-unknown-unknown -- -D warnings
        displayName: Cargo Clippy
  - stage: Release
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
    - job: Verify
      steps:
      - script: '[[ `cat CHANGELOG.md` == "## $(Build.SourceBranchName)"* ]]'
        displayName: Verify changelog was updated
      - script: '[[ `sed "3q;d" Cargo.toml` = "version = \"$(Build.SourceBranchName)"* ]]'
        displayName: Verify Cargo.toml was updated
    - job: GitHub
      dependsOn: Verify
      steps:
      - script: git clone --depth=1 --branch=1.39.1 https://github.com/WebAssembly/binaryen && cd binaryen && cmake . && make && sudo make install && cd ..
        displayName: Install dependencies (binaryen)
      - script: rustup default nightly
        displayName: Install Rust nightly
      - script: cargo install wasm-bindgen-cli wasm-pack
        displayName: Install WASM utilities
      - script: sudo npm install -g vsce
        displayName: Install dependencies (npm)
      - script: BUILDSH_RELEASE=1 ./build.sh package
        displayName: Package extension
      - script: sed '/##/q' <(tail CHANGELOG.md -n +3) | head -n -2 > github-release-changelog-diff.md
        displayName: Prepare changelog
      - task: GitHubRelease@0
        displayName: Release
        inputs:
          gitHubConnection: github/pustaczek
          repositoryName: pustaczek/icie
          releaseNotesFile: github-release-changelog-diff.md
          assets: target/evscode/icie-*.vsix
          addChangeLog: false
